### ISSUE TITLE
Android Studio Compatible Project 

### ISSUE THREAD

**Issue by Chapoly1305** [xuanxuanblingbling/NFChacker#3]
我把项目改成了Android Studio的项目了，但是太菜，还不太会用Git。
有需要的朋友可以下载来用，targetSdkVersion 25 (安卓7.1).

Just in case anyone needs to use this App with later version of Android phones. 
Not sure how to use git yet, so you may just download this Android Studio Project and import it directly. The TargetSdk is 25 which is Android 7.1. I tested it on Android 8.1 which worked just fine. 

手机需要Root，安卓Xposed框架，以及安装这个插件。
The phone need to be rooted, installed Xposed Framework and installed this addon. 

Xposed Framework - APDU Routing https://repo.xposed.info/module/at.zweng.xposed.modifyaidrouting

另外，AID 已经改成F04E66E75C02D8以便适配Xposed插件。
In addition, the AID of this Android Studio project and precompiled apk has changed AID to F04E66E75C02D8 to match this Xposed addon.

Android Studio Project: [NFChacker.zip](https://github.com/xuanxuanblingbling/NFChacker/files/4398704/NFChacker.zip)

已经编译好的APK:
Precompiled APK:
[app-debug.zip](https://github.com/xuanxuanblingbling/NFChacker/files/4398705/app-debug.zip)

祝好运
Good Luck

**Comment by xuanxuanblingbling** [comment]
我这个本身就是AS的项目呀，只不过是我把src目录抠出来了，我怕大家的gradle不一样，然后各种不过。只要在AS里新建一个工程，然后把我这个目录扔进src目录里，然后就能编译过了呀。

**Comment by xuanxuanblingbling** [comment]
> 我把项目改成了Android Studio的项目了，但是太菜，还不太会用Git。
> 有需要的朋友可以下载来用，targetSdkVersion 25 (安卓7.1).
> 
> Just in case anyone needs to use this App with later version of Android phones.
> Not sure how to use git yet, so you may just download this Android Studio Project and import it directly. The TargetSdk is 25 which is Android 7.1. I tested it on Android 8.1 which worked just fine.
> 
> 手机需要Root，安卓Xposed框架，以及安装这个插件。
> The phone need to be rooted, installed Xposed Framework and installed this addon.
> 
> Xposed Framework - APDU Routing https://repo.xposed.info/module/at.zweng.xposed.modifyaidrouting
> 
> 另外，AID 已经改成F04E66E75C02D8以便适配Xposed插件。
> In addition, the AID of this Android Studio project and precompiled apk has changed AID to F04E66E75C02D8 to match this Xposed addon.
> 
> Android Studio Project: [NFChacker.zip](https://github.com/xuanxuanblingbling/NFChacker/files/4398704/NFChacker.zip)
> 
> 已经编译好的APK:
> Precompiled APK:
> [app-debug.zip](https://github.com/xuanxuanblingbling/NFChacker/files/4398705/app-debug.zip)
> 
> 祝好运
> Good Luck

我这个本身就是AS的项目呀，只不过是我把src目录抠出来了，我怕大家的gradle不一样，然后各种不过。只要在AS里新建一个工程，然后把我这个目录扔进src目录里，然后就能编译过了呀。
